### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bitberd** [Flysre/DISCORDDISCRIMFARM#1]
Can you upload the full build or instructions?

**Comment by Flysre** [comment]
Nothing needed, just put tokens in the file tokens.txt and fire it up, send me a screen if you have a problem

**Comment by bitberd** [comment]
![Annotation 2019-10-05 130225](https://user-images.githubusercontent.com/23519467/66259630-6813eb00-e770-11e9-9f42-bd75f1d20fd3.png)

Here is a screenshot

**Comment by Flysre** [comment]
node DISCRIMFARMER.js

**Comment by bitberd** [comment]
Getting Error: Cannot find module 'discord.js' even after doing npm install discord

**Comment by Flysre** [comment]
Do each line : 


npm i randomatic
npm i discord.js
npm i system-sleep


then
node DISCORDFARMER.js

**Comment by bitberd** [comment]
`PS C:\Users\jon\Desktop\DISCORDDISCRIMFARM-master> node DISCORDFARMER.js                                                              internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\jon\Desktop\DISCORDDISCRIMFARM-master\DISCORDFARMER.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

**Comment by Flysre** [comment]
node DISCRIMFARMER.js 

sorry

**Comment by bitberd** [comment]
thanks!
